### ISSUE TITLE
Vertical offset on newer Avalonia versions

### ISSUE THREAD

**Issue by jordi-z80** [jupahe64/Avalonia.UpDock#1]
Hi, thanks for the lib! Quite useful and the most up-to-date one for Avalonia.

When updating the packages to latest (11.1.3 as I'm writing) docking the windows is harder because there's a kind of vertical offset added to the drop zones. If you want to drop the docker window you have to point slightly higher.

**Comment by jupahe64** [comment]
yeah it seems the overlay window (that draws the indicators) is misaligned
![image](https://github.com/user-attachments/assets/be2c3ffa-702c-43fd-b2fa-d2ab54e0a3f3)
not sure what up with that but it should be easy to fix

**Comment by jupahe64** [comment]
btw I can't bump up to 11.1.3 because Semi.Avalonia (a custom theme I use for testing) is at 11.1.0.2
but it seems the issue is already present in that version so just bumping up to 11.1.0 and fixing the issue should be good enough
